<?php
#-------------------------------------------------------------------------------
# Copyright 2019 NAVER Corp
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not
# use this file except in compliance with the License.  You may obtain a copy
# of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
# License for the specific language governing permissions and limitations under
# the License.
#-------------------------------------------------------------------------------

namespace Plugins;
use Yii;
use YiiBase;
use CException;


class PinpointYiiClassLoader
{
    /**
     * copy from yii autoload
     */
    public static function findFile($className)
    {
        $cpath =null;

        $coreClasses = \Closure::bind(function (){
            return YiiBase::$_coreClasses;
        },null,'YiiBase')();

        $includePaths = \Closure::bind(
            function (){
                return YiiBase::$_includePaths;
            },null,'YiiBase')();

        if(isset(Yii::$classMap[$className]))
        {
            $cpath = Yii::$classMap[$className];
        }
        elseif(isset($coreClasses[$className]))
        {
            $cpath = YII_PATH.$coreClasses[$className];
        }
        else
        {
            // include class file relying on include_path
            if(strpos($className,'\\')===false)  // class without namespace
            {
                if(Yii::$enableIncludePath===false)
                {

                    foreach($includePaths as $path)
                    {
                        $classFile=$path.DIRECTORY_SEPARATOR.$className.'.php';
                        if(is_file($classFile))
                        {
                            if(YII_DEBUG && basename(realpath($classFile))!==$className.'.php')
                                throw new CException(Yii::t('yii','Class name "{class}" does not match class file "{file}".', array(
                                    '{class}'=>$className,
                                    '{file}'=>$classFile,
                                )));
                            $cpath = $classFile;
                            break;
                        }
                    }
                }
                else
                {
                    $cpath = $className.'.php';
                }

            }
            else  // class name with namespace in PHP 5.3
            {
                $namespace=str_replace('\\','.',ltrim($className,'\\'));
                if(($path=Yii::getPathOfAlias($namespace))!==false && is_file($path.'.php'))
                    $cpath = $path.'.php';
            }
        }
//        echo $className.'  '.$cpath."<br>";
        return $cpath;
    }

    public static function autoload($className)
    {
        Yii::autoload($className); // TODO: Change the autogenerated stub
    }
}
